version: '3.8'

services:
  mattle-fun:
    container_name: mattle-fun
    build: .
    image: mattle-fun
    ports:
      - "3005:3005"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./public:/app/public
    env_file:
      - .env
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
